// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA787R3F9UyDTNXbJTONJkxFSlBTqcf6w',
    appId: '1:853814822136:web:3614ba3dcef1476ca4670d',
    messagingSenderId: '853814822136',
    projectId: 'flutterfinal-85827',
    authDomain: 'flutterfinal-85827.firebaseapp.com',
    storageBucket: 'flutterfinal-85827.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2-QTmAtogI9WK073WzZy4A_IFc63tnM',
    appId: '1:853814822136:android:3b9759c8c23dcdb6a4670d',
    messagingSenderId: '853814822136',
    projectId: 'flutterfinal-85827',
    storageBucket: 'flutterfinal-85827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmDaCwpYs3zkQUnf_t5Y_5RpyFdQX19Kc',
    appId: '1:853814822136:ios:4e78f5631569d9e6a4670d',
    messagingSenderId: '853814822136',
    projectId: 'flutterfinal-85827',
    storageBucket: 'flutterfinal-85827.appspot.com',
    iosClientId: '853814822136-uchagi7ptb1qhf4gncdul7mrdl7ldhs6.apps.googleusercontent.com',
    iosBundleId: 'com.ibrahimsheikh.finalTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmDaCwpYs3zkQUnf_t5Y_5RpyFdQX19Kc',
    appId: '1:853814822136:ios:39fea879c6de428ca4670d',
    messagingSenderId: '853814822136',
    projectId: 'flutterfinal-85827',
    storageBucket: 'flutterfinal-85827.appspot.com',
    iosClientId: '853814822136-7qs3l0bahtf89mh3qcf7ij1ucn4jr4hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalTemplate.RunnerTests',
  );
}
